name: push

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".forestry/**"

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Publish to Docker Registry
        uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          tag_with_sha: true
      - name: Update Swarm
        if: github.ref == 'refs/heads/master'
        run: |
          export sha="${{ github.sha }}"
          curl -fs -X POST ${{ secrets.SWARM_HOOK }} \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          -d 'service=maxmeuk_web' \
          -d "tag=sha-${sha:0:7}" \
          -d "image=${{ github.repository }}" \
          -d "token=${{ secrets.HOOK_TOKEN }}"
